// JARVISCertPinningTests.swift
// JARVIS digital-personhood project — GMRI
//
// Unit tests for JARVISCertPinning.swift
// Tests are self-contained: no live network, test fixture certs embedded as DER.
//
// Test matrix:
//   TC-1: Valid pin    — cert SPKI matches stored pin → .success
//   TC-2: Invalid pin  — cert SPKI does NOT match stored pin → .failure(.pinMismatch)
//   TC-3: Wrong host   — host not in pin store → .failure(.hostNotPinned)
//   TC-4: Expired cert — OS trust evaluation rejects (expiry is OS-enforced);
//                        pin logic still extracts and evaluates SPKI correctly.
//                        The full URLSession flow would cancel on OS trust failure
//                        before pin check; the SPKI extraction itself is unaffected
//                        by expiry date — tested via validateCertPin() directly.
//
// All four test fixture certs were generated by:
//   openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:P-256 ...
// SPKI pins were extracted by tools/extract_spki_pin.sh.
//
// Swift 5.9+ | macOS 14+ | iOS 17+ | watchOS 10+
// XCTest framework.

import XCTest
import Foundation
import Security
@testable import JARVISCertPinning  // adjust module name to match Package.swift target

// MARK: - Fixture data

/// Test fixture certs (DER, base64-encoded).
/// Generated 2026-05-24. Deterministic EC P-256 self-signed certs.
private enum TestFixtures {

    /// CN=test.jarvis.internal — valid (expires 2036-05-21)
    /// SPKI SHA-256: Decreb4tbND/uNMBxd5MQXGPfccTHvl2gMG4Z2MH3vQ=
    static let validCertDER = Data(base64Encoded: """
        MIIByzCCAXGgAwIBAgIUM3228cddbn2GHMMygpHDsJbQrj0wCgYIKoZIzj0EAwIw
        OzEdMBsGA1UEAwwUdGVzdC5qYXJ2aXMuaW50ZXJuYWwxDTALBgNVBAoMBEdNUkkx
        CzAJBgNVBAYTAlVTMB4XDTI2MDUyNDAxMzU1NFoXDTM2MDUyMTAxMzU1NFowOzEd
        MBsGA1UEAwwUdGVzdC5qYXJ2aXMuaW50ZXJuYWwxDTALBgNVBAoMBEdNUkkxCzAJ
        BgNVBAYTAlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEI9wswv+4Ef9COc5/
        9WDqBDVBFZluoSnNHu2GAS4Bb3fwyU3KIu3qg5pFAtBuUKkx2UxcuKqR13p/yfIk
        NOyXZ6NTMFEwHQYDVR0OBBYEFBVejPOwA3mmrHrmFcLMbhLxOZ5sMB8GA1UdIwQY
        MBaAFBVejPOwA3mmrHrmFcLMbhLxOZ5sMA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZI
        zj0EAwIDSAAwRQIhAJAhBvVs2pUMsvxNW8SLTXwxTeqA7wynmEGJrbdtIGKqAiAK
        JnrMi2jNpf/BDpo4lcbViRKcHsCIKLv/fsGEwvysAw==
        """, options: .ignoreUnknownCharacters)!

    /// Known SPKI pin for validCert (base64 SHA-256 of SPKI DER)
    static let validCertPin = "Decreb4tbND/uNMBxd5MQXGPfccTHvl2gMG4Z2MH3vQ="

    /// CN=expired.jarvis.internal — expired (notAfter: 2021-01-01)
    /// SPKI SHA-256: zJS6tyFucYMzWXc7j/Jhoa06d6PS4lt4QSwk6jVN08I=
    static let expiredCertDER = Data(base64Encoded: """
        MIIB0TCCAXegAwIBAgIUU3ru52bTNOWLD/WZdo5Cj4y3d3YwCgYIKoZIzj0EAwIw
        PjEgMB4GA1UEAwwXZXhwaXJlZC5qYXJ2aXMuaW50ZXJuYWwxDTALBgNVBAoMBEdN
        UkkxCzAJBgNVBAYTAlVTMB4XDTIwMDEwMTAwMDAwMFoXDTIxMDEwMTAwMDAwMFow
        PjEgMB4GA1UEAwwXZXhwaXJlZC5qYXJ2aXMuaW50ZXJuYWwxDTALBgNVBAoMBEdN
        UkkxCzAJBgNVBAYTAlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEDcEIrBtL
        ClmnZfLpt9OBI/6kYFLk8SyCllGMzjtaXeiRgpoCsa4WqE8NawJO0m3NXnI6aZ1Z
        7e9vttH/s7rvJaNTMFEwHQYDVR0OBBYEFMxxpCmOKgaarSeljUU25GAp8wS+MB8G
        A1UdIwQYMBaAFMxxpCmOKgaarSeljUU25GAp8wS+MA8GA1UdEwEB/wQFMAMBAf8w
        CgYIKoZIzj0EAwIDSAAwRQIgTa9rcPwBav9Klf+5nN0iCkfha3AH4mzx8+/U4Ip/
        li0CIQDeuJmzvmEg4mvId8hSjw00VVqgGlo3J3g2B1wvxN3knQ==
        """, options: .ignoreUnknownCharacters)!

    static let expiredCertPin = "zJS6tyFucYMzWXc7j/Jhoa06d6PS4lt4QSwk6jVN08I="

    /// CN=test.jarvis.internal — different key (pin will not match validCert)
    /// SPKI SHA-256: CDYzDujcWCrd+19wxs/bGiSZ1Pgc8ST+6LYI3QL0jMg=
    static let wrongKeyCertDER = Data(base64Encoded: """
        MIIByjCCAXGgAwIBAgIUE0P6dNOlGhvjFHw44CVW4XsSKH4wCgYIKoZIzj0EAwIw
        OzEdMBsGA1UEAwwUdGVzdC5qYXJ2aXMuaW50ZXJuYWwxDTALBgNVBAoMBEdNUkkx
        CzAJBgNVBAYTAlVTMB4XDTI2MDUyNDAxMzU1NFoXDTM2MDUyMTAxMzU1NFowOzEd
        MBsGA1UEAwwUdGVzdC5qYXJ2aXMuaW50ZXJuYWwxDTALBgNVBAoMBEdNUkkxCzAJ
        BgNVBAYTAlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQXzArRgtHz6QxCsg
        bNWhhFR+D/DelqpxwT+9xeBR6ODmbx6h3HCEGXaTgSw2SXHal8yN395/wabBlGNg
        pbZJFaNTMFEwHQYDVR0OBBYEFFnpiBBcRtAcB9YXWBC6shwmwq9IMB8GA1UdIwQY
        MBaAFFnpiBBcRtAcB9YXWBC6shwmwq9IMA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZI
        zj0EAwIDRwAwRAIgbla8tQjCE2rddXBTqziQZitmnmMr9vZ0YX0CLIKw9K4CIGdU
        7XPIBcos04ekvGyxdv3fp0aKABcWxOnFRxn4vuIB
        """, options: .ignoreUnknownCharacters)!

    static let wrongKeyCertPin = "CDYzDujcWCrd+19wxs/bGiSZ1Pgc8ST+6LYI3QL0jMg="

    // ── helper: DER bytes → SecCertificate ───────────────────────────────────
    static func secCertificate(from der: Data) -> SecCertificate {
        guard let cert = SecCertificateCreateWithData(nil, der as CFData) else {
            fatalError("Test fixture cert DER is malformed — check base64 encoding")
        }
        return cert
    }
}

// MARK: - Test cases

final class JARVISCertPinningTests: XCTestCase {

    // MARK: TC-1: Valid pin

    /// The presented cert's SPKI pin matches the stored pin → success.
    func test_TC1_validPin_succeeds() {
        let cert = TestFixtures.secCertificate(from: TestFixtures.validCertDER)
        let store = PlistPinStore(dictionary: [
            "test.jarvis.internal": [TestFixtures.validCertPin]
        ])

        let result = validateCertPin(certificate: cert, host: "test.jarvis.internal", store: store)

        switch result {
        case .success:
            break  // expected
        case .failure(let error):
            XCTFail("TC-1 FAIL: expected success, got \(error)")
        }
    }

    /// computeSPKIPin extracts the correct base64 hash from the fixture cert.
    func test_TC1_spkiExtraction_matchesKnownPin() {
        let cert = TestFixtures.secCertificate(from: TestFixtures.validCertDER)
        let computed = computeSPKIPin(from: cert)
        XCTAssertEqual(
            computed, TestFixtures.validCertPin,
            "TC-1 SPKI extraction: computed pin must equal the known fixture pin"
        )
    }

    // MARK: TC-2: Invalid pin

    /// The cert's SPKI does NOT match the stored pin (different key) → pinMismatch.
    func test_TC2_invalidPin_fails_withPinMismatch() {
        // Present the "wrong key" cert but store only the "valid cert" pin.
        let cert = TestFixtures.secCertificate(from: TestFixtures.wrongKeyCertDER)
        let store = PlistPinStore(dictionary: [
            "test.jarvis.internal": [TestFixtures.validCertPin]
        ])

        let result = validateCertPin(certificate: cert, host: "test.jarvis.internal", store: store)

        switch result {
        case .failure(.pinMismatch(let host)):
            XCTAssertEqual(host, "test.jarvis.internal")
        case .failure(let error):
            XCTFail("TC-2 FAIL: expected pinMismatch, got \(error)")
        case .success:
            XCTFail("TC-2 FAIL: expected failure but got success (pin incorrectly matched)")
        }
    }

    /// A bogus base64 pin string stored in the store should never match a real cert.
    func test_TC2_invalidPin_bogusStoredPin_fails() {
        let cert = TestFixtures.secCertificate(from: TestFixtures.validCertDER)
        let store = PlistPinStore(dictionary: [
            "test.jarvis.internal": ["AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="]
        ])

        let result = validateCertPin(certificate: cert, host: "test.jarvis.internal", store: store)

        guard case .failure(.pinMismatch) = result else {
            XCTFail("TC-2 FAIL: bogus pin should cause pinMismatch")
            return
        }
    }

    // MARK: TC-3: Wrong host (host not pinned)

    /// The pin store has no entry for the requested host → hostNotPinned.
    func test_TC3_wrongHost_notPinned_fails() {
        let cert = TestFixtures.secCertificate(from: TestFixtures.validCertDER)
        let store = PlistPinStore(dictionary: [
            // Pin store only has "api.deepgram.com", not "attacker.example.com"
            "api.deepgram.com": [TestFixtures.validCertPin]
        ])

        let result = validateCertPin(
            certificate: cert,
            host: "attacker.example.com",
            store: store
        )

        switch result {
        case .failure(.hostNotPinned(let host)):
            XCTAssertEqual(host, "attacker.example.com")
        case .failure(let error):
            XCTFail("TC-3 FAIL: expected hostNotPinned, got \(error)")
        case .success:
            XCTFail("TC-3 FAIL: unpinned host must not succeed")
        }
    }

    /// A cert matching the pin for host A presented for host B → hostNotPinned on B.
    func test_TC3_correctCert_wrongHost_fails() {
        let cert = TestFixtures.secCertificate(from: TestFixtures.validCertDER)
        let store = PlistPinStore(dictionary: [
            "test.jarvis.internal": [TestFixtures.validCertPin],
            // NOTE: "other.host.com" is deliberately absent
        ])

        let result = validateCertPin(
            certificate: cert,
            host: "other.host.com",
            store: store
        )

        guard case .failure(.hostNotPinned) = result else {
            XCTFail("TC-3 FAIL: cert presented for unpinned host must fail")
            return
        }
    }

    // MARK: TC-4: Expired certificate

    /// TC-4a: SPKI pin logic itself is unaffected by cert expiry.
    /// The pin layer validates the public key, not the validity window.
    /// Expiry enforcement is the OS TLS layer's responsibility (SecTrustEvaluateWithError).
    /// This test confirms that computeSPKIPin() still extracts a correct pin from
    /// an expired cert, and that validateCertPin() matches it — so the two-layer
    /// design (OS trust + pin check) is correct: OS blocks expired, pin checks key.
    func test_TC4_expiredCert_spkiExtractionStillWorks() {
        let cert = TestFixtures.secCertificate(from: TestFixtures.expiredCertDER)
        let computed = computeSPKIPin(from: cert)
        XCTAssertEqual(
            computed, TestFixtures.expiredCertPin,
            "TC-4a: SPKI extraction must succeed on expired cert (key is still valid)"
        )
    }

    /// TC-4b: An expired cert with a known pin passes validateCertPin()
    /// (pin layer does NOT check expiry — that is the OS layer's job).
    func test_TC4_expiredCert_pinMatchesStoredPin() {
        let cert = TestFixtures.secCertificate(from: TestFixtures.expiredCertDER)
        let store = PlistPinStore(dictionary: [
            "expired.jarvis.internal": [TestFixtures.expiredCertPin]
        ])

        let result = validateCertPin(
            certificate: cert,
            host: "expired.jarvis.internal",
            store: store
        )

        // The pin layer must succeed (it validates the key, not the validity window).
        // The full URLSession flow will fail BEFORE calling pin validation because
        // SecTrustEvaluateWithError rejects expired certs at the OS level.
        switch result {
        case .success:
            break  // correct — pin layer is unaffected by expiry
        case .failure(let error):
            XCTFail("TC-4b FAIL: pin validation should not be the expiry enforcer; got \(error)")
        }
    }

    /// TC-4c: In the JARVISPinningDelegate flow, expired cert is rejected
    /// BEFORE pin check because OS trust evaluation fails.
    /// This test documents the behavior via SecTrustEvaluateWithError directly.
    func test_TC4_expiredCert_osRejectsBeforePinCheck() {
        let cert = TestFixtures.secCertificate(from: TestFixtures.expiredCertDER)

        // Build a SecTrust that will fail OS evaluation (no anchor = untrusted + expired)
        var trust: SecTrust?
        let policy = SecPolicyCreateBasicX509()
        let status = SecTrustCreateWithCertificates(cert, policy, &trust)
        XCTAssertEqual(status, errSecSuccess, "TC-4c: SecTrustCreateWithCertificates must succeed")
        guard let secTrust = trust else {
            XCTFail("TC-4c: Failed to create SecTrust"); return
        }

        var trustError: CFError?
        let osPassed = SecTrustEvaluateWithError(secTrust, &trustError)

        // OS MUST reject this cert (expired + self-signed + no trusted anchor)
        XCTAssertFalse(osPassed, "TC-4c: OS TLS evaluation must reject an expired cert")
        XCTAssertNotNil(trustError, "TC-4c: OS must provide a trust error for the expired cert")
    }

    // MARK: - Backup pin (chain pin) tests

    /// Intermediate CA pin in the store matches when leaf SPKI is not listed.
    /// This exercises the backup pin path (e.g., during a leaf cert rotation window).
    func test_backupPin_intermediateMatchSuffices() {
        // Put only the wrong-key cert's pin in the store (simulates leaf rotation).
        // But also add it as a "backup" — use the wrong key cert's pin as primary
        // and valid cert's pin as backup. Present the valid cert → backup pin matches.
        let cert = TestFixtures.secCertificate(from: TestFixtures.validCertDER)
        let store = PlistPinStore(dictionary: [
            "test.jarvis.internal": [
                TestFixtures.wrongKeyCertPin,  // primary (old leaf, not matching)
                TestFixtures.validCertPin,     // backup (new leaf, matches)
            ]
        ])

        let result = validateCertPin(certificate: cert, host: "test.jarvis.internal", store: store)
        guard case .success = result else {
            XCTFail("Backup pin path failed — valid cert should match via backup pin")
            return
        }
    }

    // MARK: - Store tests

    func test_plistPinStore_emptyDict_returnsNoPins() {
        let store = PlistPinStore(dictionary: [:])
        XCTAssertTrue(store.pins(for: "api.deepgram.com").isEmpty)
        XCTAssertFalse(store.isPinned(host: "api.deepgram.com"))
    }

    func test_plistPinStore_exactMatch() {
        let store = PlistPinStore(dictionary: ["api.deepgram.com": ["pin1", "pin2"]])
        XCTAssertEqual(store.pins(for: "api.deepgram.com"), ["pin1", "pin2"])
    }

    func test_plistPinStore_wildcardMatch() {
        let store = PlistPinStore(dictionary: ["*.github.com": ["pin1"]])
        XCTAssertEqual(store.pins(for: "api.github.com"), ["pin1"])
        XCTAssertEqual(store.pins(for: "uploads.github.com"), ["pin1"])
        // Exact domain without subdomain: *.github.com should NOT match github.com
        XCTAssertTrue(store.pins(for: "github.com").isEmpty)
    }
}
