// cert_pinning_tests.cpp
// JARVIS digital-personhood project — GMRI
//
// Unit tests for cert_pinning.{h,cpp}.
// Self-contained: no live network. Test fixture certs are DER-encoded blobs
// generated by:
//   openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:P-256 ...
//
// Test matrix:
//   TC-1: Valid pin    — cert SPKI matches stored pin → PinResult::Valid
//   TC-2: Invalid pin  — cert SPKI does NOT match stored pin → PinResult::Mismatch
//   TC-3: Wrong host   — host not in pin store → PinResult::HostNotPinned
//   TC-4: Expired cert — SPKI extraction still works (expiry is TLS stack's job);
//                        validate_leaf_cert returns Valid if pin matches (correct).
//
// Build:
//   clang++ -std=c++20 -o cert_pinning_tests \
//       cert_pinning_tests.cpp cert_pinning.cpp \
//       $(pkg-config --cflags --libs libcurl openssl)
//   ./cert_pinning_tests
//
// C++20 | OpenSSL ≥ 1.1 | libcurl with OpenSSL backend

#include "cert_pinning.h"

#include <cstdio>
#include <cstring>
#include <functional>
#include <string>
#include <vector>

// OpenSSL for loading test fixture certs
#include <openssl/bio.h>
#include <openssl/pem.h>
#include <openssl/x509.h>

namespace {

// ── Minimal test harness ─────────────────────────────────────────────────────

struct TestResult {
    int passed = 0;
    int failed = 0;
    int total  = 0;
};

static TestResult g_results;

#define EXPECT_EQ(a, b, msg)                                                   \
    do {                                                                        \
        ++g_results.total;                                                      \
        if ((a) == (b)) {                                                       \
            ++g_results.passed;                                                 \
        } else {                                                                \
            ++g_results.failed;                                                 \
            std::fprintf(stderr, "  FAIL [%s:%d]: %s\n", __FILE__, __LINE__, msg); \
        }                                                                       \
    } while (0)

#define EXPECT_TRUE(expr, msg)   EXPECT_EQ(!!(expr), true, msg)
#define EXPECT_FALSE(expr, msg)  EXPECT_EQ(!!(expr), false, msg)
#define EXPECT_NE(a, b, msg)                                                   \
    do {                                                                        \
        ++g_results.total;                                                      \
        if ((a) != (b)) {                                                       \
            ++g_results.passed;                                                 \
        } else {                                                                \
            ++g_results.failed;                                                 \
            std::fprintf(stderr, "  FAIL [%s:%d]: %s\n", __FILE__, __LINE__, msg); \
        }                                                                       \
    } while (0)

void run_test(const char* name, std::function<void()> fn) {
    std::printf("  %-60s ", name);
    fn();
    std::printf("\n");
}

// ── Test fixture DER data (base64-encoded, generated 2026-05-24) ─────────────

// Valid EC P-256 cert: CN=test.jarvis.internal, expires 2036-05-21
// SPKI SHA-256: Decreb4tbND/uNMBxd5MQXGPfccTHvl2gMG4Z2MH3vQ=
static const char kValidCertDERb64[] =
    "MIIByzCCAXGgAwIBAgIUM3228cddbn2GHMMygpHDsJbQrj0wCgYIKoZIzj0EAwIw"
    "OzEdMBsGA1UEAwwUdGVzdC5qYXJ2aXMuaW50ZXJuYWwxDTALBgNVBAoMBEdNUkkx"
    "CzAJBgNVBAYTAlVTMB4XDTI2MDUyNDAxMzU1NFoXDTM2MDUyMTAxMzU1NFowOzEd"
    "MBsGA1UEAwwUdGVzdC5qYXJ2aXMuaW50ZXJuYWwxDTALBgNVBAoMBEdNUkkxCzAJ"
    "BgNVBAYTAlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEI9wswv+4Ef9COc5/"
    "9WDqBDVBFZluoSnNHu2GAS4Bb3fwyU3KIu3qg5pFAtBuUKkx2UxcuKqR13p/yfIk"
    "NOyXZ6NTMFEwHQYDVR0OBBYEFBVejPOwA3mmrHrmFcLMbhLxOZ5sMB8GA1UdIwQY"
    "MBaAFBVejPOwA3mmrHrmFcLMbhLxOZ5sMA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZI"
    "zj0EAwIDSAAwRQIhAJAhBvVs2pUMsvxNW8SLTXwxTeqA7wynmEGJrbdtIGKqAiAK"
    "JnrMi2jNpf/BDpo4lcbViRKcHsCIKLv/fsGEwvysAw==";
static const char kValidCertPin[] = "Decreb4tbND/uNMBxd5MQXGPfccTHvl2gMG4Z2MH3vQ=";

// Expired EC P-256 cert: CN=expired.jarvis.internal, notAfter=2021-01-01
// SPKI SHA-256: zJS6tyFucYMzWXc7j/Jhoa06d6PS4lt4QSwk6jVN08I=
static const char kExpiredCertDERb64[] =
    "MIIB0TCCAXegAwIBAgIUU3ru52bTNOWLD/WZdo5Cj4y3d3YwCgYIKoZIzj0EAwIw"
    "PjEgMB4GA1UEAwwXZXhwaXJlZC5qYXJ2aXMuaW50ZXJuYWwxDTALBgNVBAoMBEdN"
    "UkkxCzAJBgNVBAYTAlVTMB4XDTIwMDEwMTAwMDAwMFoXDTIxMDEwMTAwMDAwMFow"
    "PjEgMB4GA1UEAwwXZXhwaXJlZC5qYXJ2aXMuaW50ZXJuYWwxDTALBgNVBAoMBEdN"
    "UkkxCzAJBgNVBAYTAlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEDcEIrBtL"
    "ClmnZfLpt9OBI/6kYFLk8SyCllGMzjtaXeiRgpoCsa4WqE8NawJO0m3NXnI6aZ1Z"
    "7e9vttH/s7rvJaNTMFEwHQYDVR0OBBYEFMxxpCmOKgaarSeljUU25GAp8wS+MB8G"
    "A1UdIwQYMBaAFMxxpCmOKgaarSeljUU25GAp8wS+MA8GA1UdEwEB/wQFMAMBAf8w"
    "CgYIKoZIzj0EAwIDSAAwRQIgTa9rcPwBav9Klf+5nN0iCkfha3AH4mzx8+/U4Ip/"
    "li0CIQDeuJmzvmEg4mvId8hSjw00VVqgGlo3J3g2B1wvxN3knQ==";
static const char kExpiredCertPin[] = "zJS6tyFucYMzWXc7j/Jhoa06d6PS4lt4QSwk6jVN08I=";

// Different key cert: same CN as valid cert, different EC key pair
// SPKI SHA-256: CDYzDujcWCrd+19wxs/bGiSZ1Pgc8ST+6LYI3QL0jMg=
static const char kWrongKeyCertDERb64[] =
    "MIIByjCCAXGgAwIBAgIUE0P6dNOlGhvjFHw44CVW4XsSKH4wCgYIKoZIzj0EAwIw"
    "OzEdMBsGA1UEAwwUdGVzdC5qYXJ2aXMuaW50ZXJuYWwxDTALBgNVBAoMBEdNUkkx"
    "CzAJBgNVBAYTAlVTMB4XDTI2MDUyNDAxMzU1NFoXDTM2MDUyMTAxMzU1NFowOzEd"
    "MBsGA1UEAwwUdGVzdC5qYXJ2aXMuaW50ZXJuYWwxDTALBgNVBAoMBEdNUkkxCzAJ"
    "BgNVBAYTAlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQXzArRgtHz6QxCsg"
    "bNWhhFR+D/DelqpxwT+9xeBR6ODmbx6h3HCEGXaTgSw2SXHal8yN395/wabBlGNg"
    "pbZJFaNTMFEwHQYDVR0OBBYEFFnpiBBcRtAcB9YXWBC6shwmwq9IMB8GA1UdIwQY"
    "MBaAFFnpiBBcRtAcB9YXWBC6shwmwq9IMA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZI"
    "zj0EAwIDRwAwRAIgbla8tQjCE2rddXBTqziQZitmnmMr9vZ0YX0CLIKw9K4CIGdU"
    "7XPIBcos04ekvGyxdv3fp0aKABcWxOnFRxn4vuIB";
static const char kWrongKeyCertPin[] = "CDYzDujcWCrd+19wxs/bGiSZ1Pgc8ST+6LYI3QL0jMg=";

// ── Fixture helpers ───────────────────────────────────────────────────────────

/// Decode a base64-encoded DER cert into an X509*. Caller owns the result.
X509* load_cert_from_der_b64(const char* b64) {
    BIO* b64_bio = BIO_new(BIO_f_base64());
    BIO* mem_bio = BIO_new_mem_buf(b64, static_cast<int>(strlen(b64)));
    BIO_set_flags(b64_bio, BIO_FLAGS_BASE64_NO_NL);
    BIO* chain = BIO_push(b64_bio, mem_bio);

    unsigned char der[4096] = {};
    int der_len = BIO_read(chain, der, sizeof(der));
    BIO_free_all(chain);

    if (der_len <= 0) { return nullptr; }

    const unsigned char* p = der;
    return d2i_X509(nullptr, &p, der_len);
}

/// RAII wrapper for X509 test fixtures.
struct X509Guard {
    X509* cert;
    explicit X509Guard(const char* b64) : cert(load_cert_from_der_b64(b64)) {}
    ~X509Guard() { if (cert) X509_free(cert); }
    X509Guard(const X509Guard&)            = delete;
    X509Guard& operator=(const X509Guard&) = delete;
};

// ── Tests ─────────────────────────────────────────────────────────────────────

void test_spki_extraction_valid_cert() {
    X509Guard g(kValidCertDERb64);
    EXPECT_TRUE(g.cert != nullptr, "fixture cert must load");
    auto pin = jarvis::security::compute_spki_pin(g.cert);
    EXPECT_EQ(pin, std::string(kValidCertPin),
              "SPKI pin must match pre-computed reference value");
}

void test_spki_extraction_expired_cert() {
    // TC-4: SPKI extraction works on expired certs (expiry is TLS stack's job)
    X509Guard g(kExpiredCertDERb64);
    EXPECT_TRUE(g.cert != nullptr, "expired fixture cert must load");
    auto pin = jarvis::security::compute_spki_pin(g.cert);
    EXPECT_EQ(pin, std::string(kExpiredCertPin),
              "TC-4: SPKI extraction must succeed on expired cert");
    EXPECT_FALSE(pin.empty(), "TC-4: pin must not be empty for expired cert");
}

void test_spki_extraction_null_cert() {
    auto pin = jarvis::security::compute_spki_pin(nullptr);
    EXPECT_TRUE(pin.empty(), "null cert must return empty pin");
}

// TC-1: Valid pin
void test_tc1_valid_pin() {
    X509Guard g(kValidCertDERb64);
    EXPECT_TRUE(g.cert != nullptr, "TC-1: fixture cert must load");

    jarvis::security::CertPinStore store;
    store.add_pins("test.jarvis.internal", {kValidCertPin});

    auto result = jarvis::security::validate_leaf_cert(g.cert, "test.jarvis.internal", store);
    EXPECT_EQ(result, jarvis::security::PinResult::Valid, "TC-1: valid pin must return Valid");
}

// TC-1b: Backup pin path — cert matches the second entry in the pin array
void test_tc1_backup_pin_matches() {
    X509Guard g(kValidCertDERb64);
    EXPECT_TRUE(g.cert != nullptr, "TC-1b: fixture cert must load");

    jarvis::security::CertPinStore store;
    // Primary pin is wrong; backup pin is correct.
    store.add_pins("test.jarvis.internal", {kWrongKeyCertPin, kValidCertPin});

    auto result = jarvis::security::validate_leaf_cert(g.cert, "test.jarvis.internal", store);
    EXPECT_EQ(result, jarvis::security::PinResult::Valid, "TC-1b: backup pin must match");
}

// TC-2: Invalid pin
void test_tc2_invalid_pin() {
    X509Guard g(kWrongKeyCertDERb64);
    EXPECT_TRUE(g.cert != nullptr, "TC-2: fixture cert must load");

    jarvis::security::CertPinStore store;
    store.add_pins("test.jarvis.internal", {kValidCertPin});  // valid cert's pin, not wrong-key's

    auto result = jarvis::security::validate_leaf_cert(g.cert, "test.jarvis.internal", store);
    EXPECT_EQ(result, jarvis::security::PinResult::Mismatch, "TC-2: mismatched pin must return Mismatch");
}

void test_tc2_bogus_pin_in_store() {
    X509Guard g(kValidCertDERb64);
    EXPECT_TRUE(g.cert != nullptr, "TC-2b: fixture cert must load");

    jarvis::security::CertPinStore store;
    store.add_pins("test.jarvis.internal",
                   {"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="});

    auto result = jarvis::security::validate_leaf_cert(g.cert, "test.jarvis.internal", store);
    EXPECT_EQ(result, jarvis::security::PinResult::Mismatch,
              "TC-2b: bogus pin must return Mismatch");
}

// TC-3: Host not pinned
void test_tc3_host_not_pinned() {
    X509Guard g(kValidCertDERb64);
    EXPECT_TRUE(g.cert != nullptr, "TC-3: fixture cert must load");

    jarvis::security::CertPinStore store;
    store.add_pins("api.deepgram.com", {kValidCertPin});

    auto result = jarvis::security::validate_leaf_cert(g.cert, "attacker.example.com", store);
    EXPECT_EQ(result, jarvis::security::PinResult::HostNotPinned,
              "TC-3: unknown host must return HostNotPinned");
}

void test_tc3_correct_cert_wrong_host_context() {
    // Cert is valid for its host, but pin store queried for a different host.
    X509Guard g(kValidCertDERb64);
    EXPECT_TRUE(g.cert != nullptr, "TC-3b: fixture cert must load");

    jarvis::security::CertPinStore store;
    store.add_pins("test.jarvis.internal", {kValidCertPin});
    // Query for a different host
    auto result = jarvis::security::validate_leaf_cert(g.cert, "other.host.com", store);
    EXPECT_EQ(result, jarvis::security::PinResult::HostNotPinned,
              "TC-3b: cert presented for unpinned host must return HostNotPinned");
}

// TC-4: Expired cert — SPKI validation is unaffected; OS TLS rejects expiry separately
void test_tc4_expired_cert_pin_logic_unaffected() {
    X509Guard g(kExpiredCertDERb64);
    EXPECT_TRUE(g.cert != nullptr, "TC-4: expired fixture cert must load");

    jarvis::security::CertPinStore store;
    store.add_pins("expired.jarvis.internal", {kExpiredCertPin});

    // Pin validation at the SPKI level is unaffected by cert expiry.
    // The TLS stack rejects expired certs before our callback fires in production.
    auto result = jarvis::security::validate_leaf_cert(g.cert, "expired.jarvis.internal", store);
    EXPECT_EQ(result, jarvis::security::PinResult::Valid,
              "TC-4: SPKI validation must succeed for expired cert with matching pin "
              "(expiry enforcement is the TLS stack's responsibility)");
}

// Default pin store sanity check
void test_default_store_populated() {
    const auto& store = jarvis::security::CertPinStore::global();

    // All five endpoint groups must be present
    EXPECT_TRUE(store.is_pinned("api.deepgram.com"),                   "default store: deepgram");
    EXPECT_TRUE(store.is_pinned("ollama.com"),                         "default store: ollama");
    EXPECT_TRUE(store.is_pinned("generativelanguage.googleapis.com"),  "default store: gemini");
    EXPECT_TRUE(store.is_pinned("aiplatform.googleapis.com"),          "default store: vertex");
    EXPECT_TRUE(store.is_pinned("api.github.com"),                     "default store: github");
    EXPECT_TRUE(store.is_pinned("api.githubcopilot.com"),              "default store: copilot");
    EXPECT_TRUE(store.is_pinned("fleet-goose-114.convex.cloud"),       "default store: convex fleet");

    // Each entry must have at least 2 pins
    EXPECT_TRUE(store.pins_for("api.deepgram.com").size() >= 2,        "deepgram: ≥2 pins");
    EXPECT_TRUE(store.pins_for("api.github.com").size() >= 2,          "github: ≥2 pins");
    EXPECT_TRUE(store.pins_for("api.githubcopilot.com").size() >= 2,   "copilot: ≥2 pins");
    EXPECT_TRUE(store.pins_for("fleet-goose-114.convex.cloud").size() >= 2, "convex: ≥2 pins");
}

void test_null_cert_returns_no_certificate() {
    jarvis::security::CertPinStore store;
    store.add_pins("test.jarvis.internal", {kValidCertPin});
    auto result = jarvis::security::validate_leaf_cert(nullptr, "test.jarvis.internal", store);
    EXPECT_EQ(result, jarvis::security::PinResult::NoCertificate,
              "null cert must return NoCertificate");
}

}  // namespace

int main() {
    std::printf("JARVIS cert_pinning unit tests\n");
    std::printf("=================================\n");

    run_test("spki_extraction: valid EC P-256 cert",        test_spki_extraction_valid_cert);
    run_test("spki_extraction: expired cert (still works)", test_spki_extraction_expired_cert);
    run_test("spki_extraction: null cert → empty",          test_spki_extraction_null_cert);
    run_test("TC-1:  valid pin matches → Valid",            test_tc1_valid_pin);
    run_test("TC-1b: backup pin path → Valid",              test_tc1_backup_pin_matches);
    run_test("TC-2:  wrong key → Mismatch",                 test_tc2_invalid_pin);
    run_test("TC-2b: bogus stored pin → Mismatch",          test_tc2_bogus_pin_in_store);
    run_test("TC-3:  unknown host → HostNotPinned",         test_tc3_host_not_pinned);
    run_test("TC-3b: wrong host context → HostNotPinned",   test_tc3_correct_cert_wrong_host_context);
    run_test("TC-4:  expired cert SPKI → Valid (pin layer pinned)", test_tc4_expired_cert_pin_logic_unaffected);
    run_test("default store: all endpoints present",        test_default_store_populated);
    run_test("null cert → NoCertificate",                   test_null_cert_returns_no_certificate);

    std::printf("\n=================================\n");
    std::printf("Results: %d/%d passed", g_results.passed, g_results.total);
    if (g_results.failed > 0) {
        std::printf(", %d FAILED\n", g_results.failed);
        return 1;
    }
    std::printf(" — ALL PASS\n");
    return 0;
}
