// cert_pinning.h
// JARVIS digital-personhood project — GMRI
//
// SPKI-based certificate pinning for the C++ native runtime's libcurl HTTP client.
// Provides a libcurl CURLOPT_SSL_CTX_FUNCTION callback that validates the peer
// certificate's SubjectPublicKeyInfo (SPKI) SHA-256 hash against an embedded pin
// table generated at build time.
//
// Design:
//   • SPKI pinning (not full-cert) — survives cert renewal with same key.
//   • Fail-closed: any validation failure returns CURLE_SSL_PINNEDPUBKEYNOTMATCH.
//   • Pin table embedded as a static lookup via pins_embedded.h (generated by
//     tools/extract_spki_pin.sh at build time).
//   • Thread-safe: CertPinStore is read-only after construction.
//   • No Python runtime dependency. No Rust.
//
// Requirements:
//   • C++20
//   • libcurl with OpenSSL backend (CURLOPT_SSL_CTX_FUNCTION requires OpenSSL/wolfSSL)
//   • OpenSSL ≥ 1.1 or LibreSSL ≥ 3.0
//
// Usage:
//   auto& store = jarvis::security::CertPinStore::global();
//   auto ctx    = jarvis::security::make_curl_pin_context("api.deepgram.com", store);
//   curl_easy_setopt(curl, CURLOPT_SSL_CTX_FUNCTION, jarvis::security::curl_ssl_ctx_cb);
//   curl_easy_setopt(curl, CURLOPT_SSL_CTX_DATA,     ctx.get());
//   // ctx must remain alive until curl_easy_perform() returns.

#pragma once

#include <array>
#include <memory>
#include <span>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

// OpenSSL and libcurl are required dependencies; include them here.
// cert_pinning.h intentionally exposes these types so callers know what they're
// working with. Both are available on every supported platform.
#include <openssl/ssl.h>
#include <openssl/x509.h>
#include <curl/curl.h>

namespace jarvis::security {

// ── SPKI pin representation ─────────────────────────────────────────────────

/// A single SPKI pin: base64(SHA-256(SubjectPublicKeyInfo DER)).
/// Stored as a 44-character base64 string (SHA-256 = 32 bytes → 44 base64 chars).
using SpkiPin = std::string;

/// Sentinel returned by computeSPKIPin on failure (empty string = no pin).
inline constexpr std::string_view kInvalidPin{};

// ── Pin validation results ──────────────────────────────────────────────────

enum class PinResult : uint8_t {
    Valid,             ///< SPKI matched a stored pin.
    Mismatch,          ///< SPKI does not match any stored pin.
    HostNotPinned,     ///< Host has no entries in the pin store.
    NoCertificate,     ///< Peer presented no certificate.
    CryptoError,       ///< SPKI extraction failed (unsupported key type, malloc failure).
};

[[nodiscard]] constexpr const char* pin_result_cstr(PinResult r) noexcept {
    switch (r) {
        case PinResult::Valid:          return "Valid";
        case PinResult::Mismatch:       return "Mismatch";
        case PinResult::HostNotPinned:  return "HostNotPinned";
        case PinResult::NoCertificate:  return "NoCertificate";
        case PinResult::CryptoError:    return "CryptoError";
    }
    return "Unknown";
}

// ── Pin store ───────────────────────────────────────────────────────────────

/// Read-only pin store.
/// Populated at construction from the embedded static table (pins_embedded.h).
/// Optionally updated at runtime (e.g., operator-authorized Secure Enclave override).
class CertPinStore {
public:
    /// Construct the global default store from the embedded pin table.
    /// Call once at startup; the returned instance is read-only.
    [[nodiscard]] static CertPinStore make_default();

    /// Singleton accessor for the global default store.
    /// Thread-safe after first call (Meyers singleton via static local).
    static const CertPinStore& global();

    /// Returns the registered SPKI pins for `host`.
    /// Returns an empty span if the host is not pinned.
    [[nodiscard]] std::span<const SpkiPin> pins_for(std::string_view host) const noexcept;

    /// Returns true if `host` has at least one registered pin.
    [[nodiscard]] bool is_pinned(std::string_view host) const noexcept;

    /// Add or overwrite the pin set for `host` (e.g., from Secure Enclave override).
    /// Only callable during initialization before any concurrent reads.
    void add_pins(std::string host, std::vector<SpkiPin> pins);

private:
    std::unordered_map<std::string, std::vector<SpkiPin>> store_;
};

// ── SPKI extraction ─────────────────────────────────────────────────────────

/// Compute base64(SHA-256(SubjectPublicKeyInfo DER)) from an OpenSSL X509 object.
/// Returns empty string on failure (unsupported key, memory allocation failure).
/// Caller does NOT take ownership of `cert`.
[[nodiscard]] SpkiPin compute_spki_pin(X509* cert) noexcept;

// ── Standalone validation ────────────────────────────────────────────────────

/// Validate a single X509 certificate against the pin store for `host`.
/// Does not check certificate validity dates — that is the TLS stack's job.
[[nodiscard]] PinResult validate_leaf_cert(
    X509*              cert,
    std::string_view   host,
    const CertPinStore& store
) noexcept;

// ── libcurl integration ──────────────────────────────────────────────────────

/// Per-request context passed to the libcurl SSL_CTX callback.
/// Must remain alive until curl_easy_perform() returns.
/// Create via make_curl_pin_context().
struct CurlPinContext {
    std::string         host;
    const CertPinStore* store;  // non-owning; global() is valid for lifetime
    PinResult           last_result{PinResult::HostNotPinned};
};

/// Allocate a CurlPinContext for `host` referencing `store`.
[[nodiscard]] std::unique_ptr<CurlPinContext> make_curl_pin_context(
    std::string         host,
    const CertPinStore& store = CertPinStore::global()
);

/// libcurl CURLOPT_SSL_CTX_FUNCTION callback.
/// Installs an OpenSSL verify callback on the SSL_CTX that extracts
/// and validates the peer's leaf-certificate SPKI against the pin store.
///
/// Registers via:
///   curl_easy_setopt(curl, CURLOPT_SSL_CTX_FUNCTION, curl_ssl_ctx_cb);
///   curl_easy_setopt(curl, CURLOPT_SSL_CTX_DATA,     ctx_ptr);
///
/// Returns CURLE_OK (0) on success, or a libcurl error code on failure.
/// The actual pin rejection happens in the OpenSSL verify callback during
/// the TLS handshake; curl_easy_perform will then return CURLE_SSL_PINNEDPUBKEYNOTMATCH.
CURLcode curl_ssl_ctx_cb(CURL* curl, void* ssl_ctx, void* userdata) noexcept;

// ── Convenience wrapper ──────────────────────────────────────────────────────

/// Install cert pinning on a CURL* handle.
/// Sets CURLOPT_SSL_CTX_FUNCTION + CURLOPT_SSL_CTX_DATA.
/// `ctx` must remain alive until curl_easy_perform() returns.
/// Returns false if curl is null.
bool install_pin_validator(
    CURL*          curl,
    CurlPinContext* ctx
) noexcept;

}  // namespace jarvis::security
