// pins_embedded.h
// AUTO-GENERATED by tools/extract_spki_pin.sh — do not edit by hand.
// Regenerate: cd apple_native/tools && ./extract_spki_pin.sh <host> 443 --chain
//
// Last extracted: 2026-05-24T01:33Z
// GMRI / JARVIS digital-personhood project
//
// Layout: each host entry has {primary_leaf_pin, intermediate_pin, [root_pin]}.
// Minimum 2 pins per host per OWASP/Chromium guidance.
// SPKI format: base64(SHA-256(SubjectPublicKeyInfo DER)).
//
// ROTATE BEFORE EXPIRY. See security/PIN_ROTATION.md.

#pragma once
#include <array>
#include <string_view>

namespace jarvis::security::pins {

// ── Deepgram STT (api.deepgram.com) ─────────────────────────────────────────
// Leaf expires: 2026-06-30 (Let's Encrypt ~90-day — rotate aggressively)
inline constexpr std::array kDeepgram = {
    std::string_view{"kKyqsiseGkGRI3huaY6YdXi59AYtdVsBSM4GuAZywbQ="},  // leaf: CN=api.deepgram.com
    std::string_view{"AlSQhgtJirc8ahLyekmtX+Iw+v46yPYRLJt9Cq1GlB0="},  // intermediate: Let's Encrypt R13
};

// ── Ollama Cloud (ollama.com) ────────────────────────────────────────────────
// Leaf expires: 2026-07-24
inline constexpr std::array kOllama = {
    std::string_view{"SlipvEbDtlXr5OGLwSGDYyr1hCku5oiYQTeiZmBkB/g="},  // leaf: CN=ollama.com
    std::string_view{"OdSlmQD9NWJh4EbcOHBxkhygPwNSwA9Q91eounfbcoE="},  // intermediate: GTS WR3
    std::string_view{"hxqRlPTu1bMS/0DITB1SSu0vd4u/8l8TjPgfaAp63Gc="},  // root: GTS Root R1
};

// ── Google OAuth authorize (accounts.google.com) ─────────────────────────────
// Leaf expires: 2026-07-30
inline constexpr std::array kGoogleAccounts = {
    std::string_view{"yEhKecNgpxgAZoXTCE7TV9Z8ZUEVzMiXy/EnUZMw/xQ="},  // leaf: CN=accounts.google.com
    std::string_view{"vh78KSg1Ry4NaqGDV10w/cTb9VH3BQUZoCWNa93W/EY="},  // intermediate: GTS WE2
    std::string_view{"mEflZT5enoR1FuXLgYYGqnVEoZvmf9c2bVBpiOjYQ0c="},  // root: GTS Root R4
};

// ── Google OAuth token/revoke (oauth2.googleapis.com) ────────────────────────
// Leaf expires: 2026-07-30
inline constexpr std::array kGoogleOAuth2 = {
    std::string_view{"eL8NRzX+CyyicuFpTYEF4XQtOPKJ/BQF3NhHKqyrnM8="},  // leaf: Google wildcard
    std::string_view{"vh78KSg1Ry4NaqGDV10w/cTb9VH3BQUZoCWNa93W/EY="},  // intermediate: GTS WE2
    std::string_view{"mEflZT5enoR1FuXLgYYGqnVEoZvmf9c2bVBpiOjYQ0c="},  // root: GTS Root R4
};

// ── Google Gemini REST (generativelanguage.googleapis.com) ───────────────────
// Leaf expires: 2026-07-30
inline constexpr std::array kGeminiRest = {
    std::string_view{"eL8NRzX+CyyicuFpTYEF4XQtOPKJ/BQF3NhHKqyrnM8="},  // leaf: Google wildcard
    std::string_view{"vh78KSg1Ry4NaqGDV10w/cTb9VH3BQUZoCWNa93W/EY="},  // intermediate: GTS WE2
    std::string_view{"mEflZT5enoR1FuXLgYYGqnVEoZvmf9c2bVBpiOjYQ0c="},  // root: GTS Root R4
};

// ── Google AI Platform / Vertex (aiplatform.googleapis.com) ─────────────────
// Same cert chain as Gemini REST (Google CDN / wildcard).
inline constexpr std::array kGeminiVertex = {
    std::string_view{"eL8NRzX+CyyicuFpTYEF4XQtOPKJ/BQF3NhHKqyrnM8="},  // leaf: Google wildcard
    std::string_view{"vh78KSg1Ry4NaqGDV10w/cTb9VH3BQUZoCWNa93W/EY="},  // intermediate: GTS WE2
    std::string_view{"mEflZT5enoR1FuXLgYYGqnVEoZvmf9c2bVBpiOjYQ0c="},  // root: GTS Root R4
};

// ── GitHub OAuth authorize/token (github.com) ────────────────────────────────
// Leaf expires: 2026-08-02
inline constexpr std::array kGitHubOAuth = {
    std::string_view{"Ry0vLQcAM0ZpwjfCIday3P4budz0fLwe34EWXN1ZWdk="},  // leaf: CN=github.com
    std::string_view{"ZSagvDzjltLkewXEBuDxIzpW/dpVw1Juvvmd0hhkzdY="},  // intermediate: Sectigo DV E36
    std::string_view{"sLVjNUaFYfW7n6EtgBeEpjOlcnBdNPMrZDRF36iwBdE="},  // root: Sectigo Root E46
};

// ── GitHub (api.github.com) ──────────────────────────────────────────────────
// Leaf expires: 2026-08-01
inline constexpr std::array kGitHub = {
    std::string_view{"QVnLDkTvhX8bfBbaP6XeqWLCOja893s79lYfjQc/hWI="},  // leaf: CN=*.github.com
    std::string_view{"ZSagvDzjltLkewXEBuDxIzpW/dpVw1Juvvmd0hhkzdY="},  // intermediate: Sectigo DV E36
    std::string_view{"sLVjNUaFYfW7n6EtgBeEpjOlcnBdNPMrZDRF36iwBdE="},  // root: Sectigo Root E46
};

// ── GitHub Copilot (api.githubcopilot.com) ───────────────────────────────────
// Leaf expires: 2026-07-02
inline constexpr std::array kGitHubCopilot = {
    std::string_view{"taNMyGQdN3cEnkEtpmfYjXrtYGQjbSehaWCycLuVdnY="},  // leaf: CN=*.githubcopilot.com
    std::string_view{"a9khLOZJxlnJyrxstg/P+seiDCm+Yf3OsrXyFocBaI0="},  // intermediate: Sectigo DV R36
    std::string_view{"Douxi77vs4G+Ib/BogbTFymEYq0QSFXwSgVCaZcI09Q="},  // root: Sectigo Root R46
};

// ── Convex fleet (fleet-goose-114.convex.cloud) ──────────────────────────────
// WSS uses same TLS cert as HTTPS on port 443.
// Leaf expires: 2026-07-10
inline constexpr std::array kConvex = {
    std::string_view{"iGgHCBV+8eUb8PHuMmz/rCl6Kz7bN8/ar21b1G25zbc="},  // leaf: CN=convex.cloud wildcard
    std::string_view{"kIdp6NNEd8wsugYyyIYFsi1ylMCED3hZbSR8ZFsa/A4="},  // intermediate: GTS WE1
    std::string_view{"mEflZT5enoR1FuXLgYYGqnVEoZvmf9c2bVBpiOjYQ0c="},  // root: GTS Root R4
};

// ── Build-time aggregate (used by CertPinStore::make_default()) ──────────────
struct HostPins {
    std::string_view                           host;
    std::span<const std::string_view>          pins;
};

// clang-format off
inline constexpr std::array<HostPins, 11> kAllPins{{
    { "api.deepgram.com",                    kDeepgram       },
    { "ollama.com",                          kOllama         },
    { "accounts.google.com",                 kGoogleAccounts },
    { "oauth2.googleapis.com",               kGoogleOAuth2   },
    { "generativelanguage.googleapis.com",   kGeminiRest     },
    { "aiplatform.googleapis.com",           kGeminiVertex   },
    { "github.com",                          kGitHubOAuth    },
    { "api.github.com",                      kGitHub         },
    { "api.githubcopilot.com",               kGitHubCopilot  },
    { "fleet-goose-114.convex.cloud",        kConvex         },
    { "convex.cloud",                        kConvex         },
}};
// clang-format on

}  // namespace jarvis::security::pins
